### ISSUE TITLE
Invalid URLs 'post_data_dict' and 'target_dir' followed by post access errors

### ISSUE THREAD

**Issue by kingraaa** [Tatsh/patreon-archiver#3]
Hey! That last fix to allow for nonetype worked perfectly, thanks. I am now able to download all image and text posts, but when we get to the posts that contain vimeo links I'm then greeted by some errors.

```
Image file: https://www.patreon.com/posts/XXXX
Text_Only: https://www.patreon.com/posts/XXXX
[generic] Extracting URL: post_data_dict
ERROR: [generic] None: 'post_data_dict' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:post_data_dict" ) to search YouTube
[generic] Extracting URL: target_dir
ERROR: [generic] None: 'target_dir' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:target_dir" ) to search YouTube
[Patreon] Extracting URL: https://www.patreon.com/posts/XXXX
[Patreon] 83591385: Downloading API JSON
ERROR: [Patreon] 83591385: You do not have access to this post
[Patreon] Extracting URL: https://www.patreon.com/posts/XXXX
[Patreon] Sleeping 1 seconds ...
[Patreon] 83426444: Downloading API JSON
ERROR: [Patreon] 83426444: You do not have access to this post
[Patreon] Extracting URL: https://www.patreon.com/posts/XXXX
[Patreon] Sleeping 1 seconds ...
[Patreon] 83203892: Downloading API JSON
```

I did not run the line those first errors offered, as it appears to me that they are variable names accidentally being passed as data. (And the videos are vimeo not YouTube). If this is wrong and I should run those commands to fix them, then... fair enough lol. 

I am hoping that is also the cause of the access issues (which continue to repeat for each video post). I have tried with different sleep timer intervals and this is always the exact same spot it gets stuck at. These errors repeat for different posts until the script ends

Let me know if you need any further debug info or testing :)

**Comment by Tatsh** [comment]
For the last two, this is almost certainly https://github.com/yt-dlp/yt-dlp/pull/6897 where some cookies are coming back empty (for Patreon the `session_id` cookie). I do not think I am using the yt-dlp API incorrectly here.

Could you do the following?

1. Clone [this version of yt-dlp](https://github.com/mbway/yt-dlp/tree/cookie_fixes) and get it to run (make virtualenv, install, etc).
2. Run (with that version of yt-dlp) `yt-dlp --cookies-from-browser chrome PATREON_URL`. Let me know if this works or if you still get *You do not have access to this post*.

I thought this issue was due to a configuration issue on my system (like something set in `chrome://flags`) so it might be on your end as well? You are the second one to report this issue.

Regarding my code's use of the YoutubeDL API I don't think it is incorrect. You can see how to use the YoutubeDL class programmatically in the yt-dlp readme.

And regarding the first two erroneous strings being passed to yt-dlp I need to look into it. It's probably something simple.
